"""Initial migration

Revision ID: 1a491fa994df
Revises: 
Create Date: 2025-08-29 16:14:45.369932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a491fa994df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athletes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('sport', sa.String(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('handedness', sa.String(), nullable=True),
    sa.Column('world_ranking', sa.Integer(), nullable=True),
    sa.Column('best_world_ranking', sa.Integer(), nullable=True),
    sa.Column('intl_debut_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('card_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('edition_cap', sa.Integer(), nullable=True),
    sa.Column('minted_count', sa.Integer(), nullable=False),
    sa.Column('glb_url', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('etrnl_url_group_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("version in ('regular','diamond')", name='ck_template_version'),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('serial_no', sa.Integer(), nullable=False),
    sa.Column('etrnl_tag_uid', sa.String(), nullable=True),
    sa.Column('etrnl_tag_id', sa.String(), nullable=True),
    sa.Column('last_ctr', sa.Integer(), nullable=False),
    sa.Column('tamper_status', sa.String(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('unassigned', 'shipped', 'claimed', name='cardstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['card_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_instances_etrnl_tag_id'), ['etrnl_tag_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_card_instances_etrnl_tag_uid'), ['etrnl_tag_uid'], unique=True)

    op.create_table('scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_instance_id', sa.UUID(), nullable=True),
    sa.Column('tag_id', sa.String(), nullable=True),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('ctr', sa.Integer(), nullable=True),
    sa.Column('authentic', sa.Boolean(), nullable=True),
    sa.Column('tt_curr', sa.String(), nullable=True),
    sa.Column('tt_perm', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['card_instance_id'], ['card_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scans')
    with op.batch_alter_table('card_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_instances_etrnl_tag_uid'))
        batch_op.drop_index(batch_op.f('ix_card_instances_etrnl_tag_id'))

    op.drop_table('card_instances')
    op.drop_table('card_templates')
    op.drop_table('users')
    op.drop_table('athletes')
    # ### end Alembic commands ###
