"""add action_photo_url to athletes

Revision ID: 1eb9c2618806
Revises: 410df16580e8
Create Date: 2025-10-14 04:11:39.022001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eb9c2618806'
down_revision = '410df16580e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athletes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action_photo_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athletes', schema=None) as batch_op:
        batch_op.drop_column('action_photo_url')

    # ### end Alembic commands ###
