"""add location and date_of_birth to users

Revision ID: 249fede72d9d
Revises: 76a666c23286
Create Date: 2025-10-17 18:34:51.954579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249fede72d9d'
down_revision = '76a666c23286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if columns already exist before adding them
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = [col['name'] for col in inspector.get_columns('users')]
    
    if 'location' not in columns or 'date_of_birth' not in columns:
        with op.batch_alter_table('users', schema=None) as batch_op:
            if 'location' not in columns:
                batch_op.add_column(sa.Column('location', sa.String(), nullable=True))
            if 'date_of_birth' not in columns:
                batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
