"""add_qualification_image_url_to_athletes

Revision ID: 2c04799c4776
Revises: 2433c7de71f9
Create Date: 2025-10-16 14:38:32.317946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c04799c4776'
down_revision = '2433c7de71f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column already exists before adding it
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = [col['name'] for col in inspector.get_columns('athletes')]
    
    if 'qualification_image_url' not in columns:
        with op.batch_alter_table('athletes', schema=None) as batch_op:
            batch_op.add_column(sa.Column('qualification_image_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athletes', schema=None) as batch_op:
        batch_op.drop_column('qualification_image_url')

    # ### end Alembic commands ###
