"""Add quote_photo_url to athletes

Revision ID: 45658664cca1
Revises: 880992a02a5c
Create Date: 2025-10-14 01:37:15.930231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45658664cca1'
down_revision = '880992a02a5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athletes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quote_photo_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athletes', schema=None) as batch_op:
        batch_op.drop_column('quote_photo_url')

    # ### end Alembic commands ###
