"""remove_unique_constraint_from_template_code

Revision ID: b15c7b11405c
Revises: 249fede72d9d
Create Date: 2025-10-19 13:17:30.678500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b15c7b11405c'
down_revision = '249fede72d9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_templates_template_code'))
        batch_op.create_index(batch_op.f('ix_card_templates_template_code'), ['template_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_templates_template_code'))
        batch_op.create_index(batch_op.f('ix_card_templates_template_code'), ['template_code'], unique=True)

    # ### end Alembic commands ###
