"""add card_back_url to athletes

Revision ID: 2433c7de71f9
Revises: 1eb9c2618806
Create Date: 2025-10-14 05:43:34.077478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2433c7de71f9'
down_revision = '1eb9c2618806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column already exists before adding it
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = [col['name'] for col in inspector.get_columns('athletes')]
    
    if 'card_back_url' not in columns:
        with op.batch_alter_table('athletes', schema=None) as batch_op:
            batch_op.add_column(sa.Column('card_back_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athletes', schema=None) as batch_op:
        batch_op.drop_column('card_back_url')

    # ### end Alembic commands ###
