"""password auth fields

Revision ID: 731597f66fda
Revises: 1a491fa994df
Create Date: 2025-09-02 22:54:32.449918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '731597f66fda'
down_revision = '1a491fa994df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('google_sub', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_google_sub'), ['google_sub'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_google_sub'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('google_sub')
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
