"""add series_number and card_number to athletes

Revision ID: 76a666c23286
Revises: 2c04799c4776
Create Date: 2025-10-16 23:29:10.162710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a666c23286'
down_revision = '2c04799c4776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athletes', schema=None) as batch_op:
        # Add columns as nullable first
        batch_op.add_column(sa.Column('series_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('card_number', sa.Integer(), nullable=True))
    
    # Set default values for existing athletes
    op.execute("UPDATE athletes SET series_number = 1 WHERE series_number IS NULL")
    
    # Assign unique card numbers to existing athletes (001-009)
    op.execute("""
        UPDATE athletes 
        SET card_number = CASE 
            WHEN full_name = 'Brady Ellison' THEN 1
            WHEN full_name = 'Mete Gazoz' THEN 2
            WHEN full_name = 'Ella Gibson' THEN 3
            WHEN full_name = 'Deepika Kumari' THEN 4
            WHEN full_name = 'Sara López' THEN 5
            WHEN full_name = 'Mike Schloesser' THEN 6
            WHEN full_name = 'Lim Sihyeon' THEN 7
            WHEN full_name = 'Mathias Fullerton' THEN 8
            WHEN full_name = 'Kim Woojin' THEN 9
            ELSE 1
        END
        WHERE card_number IS NULL
    """)
    
    # Now make series_number NOT NULL
    with op.batch_alter_table('athletes', schema=None) as batch_op:
        batch_op.alter_column('series_number', nullable=False)
        batch_op.create_index(batch_op.f('ix_athletes_card_number'), ['card_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athletes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_athletes_card_number'))
        batch_op.drop_column('card_number')
        batch_op.drop_column('series_number')

    # ### end Alembic commands ###
