"""add name, make password nullable

Revision ID: 91274cbc56ad
Revises: 95d713ff0b0f
Create Date: 2025-09-03 01:11:23.192230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91274cbc56ad'
down_revision = '95d713ff0b0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('name')

    # ### end Alembic commands ###
